# Generated by Django 4.0.1 on 2023-11-23 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_agenda_run_alter_agenda_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='run',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="El número debe estar en el algunos de los siguientes formatos: '1.111.111-1' o '11.111.111-1'.", regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-\\d{1}$')], verbose_name='run'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='run',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message="El número debe estar en el algunos de los siguientes formatos: '1.111.111-1' o '11.111.111-1'.", regex='^\\d{1,2}\\.\\d{3}\\.\\d{3}-\\d{1}$')], verbose_name='run'),
        ),
    ]
