# Generated by Django 4.0.1 on 2023-11-21 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_centro'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicos.centro'),
            preserve_default=False,
        ),
    ]
